# Theme settings
dox:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Project Name
            image:
        nav:
            - item_name: Item 1
              item_url: '#'
            - item_name: Item 2
              item_url: '#'
            - item_name: Item 3
              item_url: '#'
        cta:
            label: CTA Label
            url: https://example.com/
    footer:
        content:
            logo:
                text: Project name
                image:
            text: Copyright &copy; 2018. - Project name <br>All rights reserved.
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# Defining collections
collections:
    documentation:
        output: true

# Defining defaults
defaults:
    -
        scope:
            path: ''
            type: 'documentation'
        values:
            layout: 'documentation-single'

# SASS settings
sass:
    sass_dir: ./dox-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./dox-theme/_layouts
includes_dir: ./dox-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
